# Generated by Django 5.0.4 on 2024-05-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_create_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="profile_avatars/avatar.png", upload_to="profile_avatars"
            ),
        ),
    ]
