# Generated by Django 5.0.4 on 2024-08-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_deleting_orphan_accidentally_created_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
