services:
  django_gunicorn:
    volumes:
      - static_volume:/var/www/iaro-project/static   # mount volume for static files
      - media_volume:/var/www/iaro-project/media     # mount volume for media
      - ./db:/app/db     # mount host dir ./db to container path /app/db for sqlite
    env_file:
      - ./.env           # environment variables for django
    build:
      context: .         # context for build (current directory)
    expose:
      - "8000"           # expose port 8000 for django app inside docker for other services
    depends_on:
      - memcached        # ensure memcached starts before django_gunicorn

  nginx:
    build: ./nginx       # build nginx from specified directory
    volumes:
      - static_volume:/var/www/iaro-project/static   # share static volume with nginx
      - media_volume:/var/www/iaro-project/media     # share media volume with nginx
      #- ./host/path/nginx/logs:/var/log/nginx        # nginx logs
      - ./certs:/etc/letsencrypt                     # certbot ssl certificates
    ports:
      - "1337:80"          # expose port 1337 for nginx outside of docker
      - "443:443"
    depends_on:
      - django_gunicorn  # start after django_gunicorn

  memcached:
    image: memcached:alpine
    ports: # maybe just use expose?
      - "11213:11213"           # expose port 11213 for memcached
    command:
      - '-m 128'

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/var/lib/letsencrypt
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - DOMAINS=rybniismak.com
      - EMAIL=igor@iaro.co


volumes:
  static_volume:                # define volume for static files
  media_volume:                 # define volume for media files
