services:
  django_gunicorn:
    volumes:
      - static_volume:/var/www/iaro-project/static:rw   # mount volume for static files
      - media_volume:/var/www/iaro-project/media:rw     # mount volume for media
      - ./db:/app/db:rw                              # mount host dir to container
    env_file:
      - ./.env           # environment variables for django
    build:
      context: .         # context for build (current directory)
    expose:
      - "8000"           # expose port 8000 for django app inside docker for other services
    depends_on:
      - memcached        # ensure memcached starts before django_gunicorn
    restart: always

  nginx:
    build: ./nginx       # build nginx from specified directory
    volumes:
      - static_volume:/var/www/iaro-project/static:rw   # share static volume with nginx
      - media_volume:/var/www/iaro-project/media:rw     # share media volume with nginx
    ports:
      - "80:80"          # expose port 1337 for nginx outside of docker
      - "443:443"
    depends_on:
      - django_gunicorn  # start after django_gunicorn
    restart: always

  memcached:
    image: memcached:alpine
    ports: # maybe just use expose?
      - "11213:11213"           # expose port 11213 for memcached
    command:
      - '-m 128'

volumes:
  static_volume:                # define volume for static files
  media_volume:                 # define volume for media files
