version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static_volume:/var/www/iaro-project/static   # mount volume for static files
      - media_volume:/var/www/iaro-project/media     # mount volume for media
      - ./db:/app/db     # mount host dir ./db to container path /app/db for sqlite
    env_file:
      - ./.env           # environment variables for django
    build:
      context: .         # context for build (current directory)
    expose:
      - "8000"      # expose port 8000 for django app
    depends_on:
      - memcached        # ensure memcached starts before django_gunicorn

  nginx:
    build: ./nginx       # build nginx from specified directory
    volumes:
      - static_volume:/var/www/iaro-project/static   # share static volume with nginx
      - media_volume:/var/www/iaro-project/media     # share media volume with nginx
      - ./host/path/nginx/logs:/var/log/nginx        # nginx logs
    ports:
      - "1337:80"          # expose port 80 for nginx
    depends_on:
      - django_gunicorn  # start after django_gunicorn

  memcached:
    image: memcached:alpine
    ports:
      - "11213:11213"           # expose port 11211 for memcached
    command:
      - '-m 128'

volumes:
  static_volume:                # define volume for static files
  media_volume:                 # define volume for media files
