# Generated by Django 5.0.4 on 2024-08-10 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0047_alter_branch_departmentid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="profile_avatars/avatar.png",
                        upload_to="profile_avatars",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        default=employees.models.get_first_branch_id,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
