# Generated by Django 5.0.4 on 2024-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_move_data_from_profile_to_employee_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="planday_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
