# Generated by Django 5.0.4 on 2024-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_populate_planday_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
