# Generated by Django 5.0.4 on 2024-11-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_populate_employee_names"),
        ("onboarding", "0014_alter_document_assigned_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="onboarding_stages",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="personal_information_form",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to="onboarding.personalinformation",
            ),
        ),
    ]
