# Generated by Django 5.1.3 on 2024-11-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_create_personal_info_for_existing_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='organisation_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
