# Generated by Django 5.1.3 on 2024-11-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeprofile_organisation_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='organisation_role',
        ),
    ]
