# Generated by Django 5.0.4 on 2024-06-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0001_initial"),
        ("inventory", "0036_rename_technical_name_branch_tech_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="branches",
            field=models.ManyToManyField(
                blank=True, related_name="branch_notes", to="inventory.branch"
            ),
        ),
    ]
