# Generated by Django 5.0.4 on 2024-06-25 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_note_branches"),
        ("inventory", "0036_rename_technical_name_branch_tech_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["timestamp"], name="interaction_timesta_7ccd13_idx"
            ),
        ),
    ]
