# Generated by Django 5.0.4 on 2024-06-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_note_interaction_timesta_7ccd13_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
