# Generated by Django 5.0.4 on 2024-06-27 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_remove_note_is_read_notereadstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notereadstatus",
            index=models.Index(
                fields=["user", "is_read"], name="interaction_user_id_29b51d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notereadstatus",
            index=models.Index(
                fields=["note", "user"], name="interaction_note_id_0190d9_idx"
            ),
        ),
    ]
