# Generated by Django 5.0.4 on 2024-07-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "interactions",
            "0009_learningcategory_alter_video_description_pdfupload_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningcategory",
            options={
                "verbose_name": "Learning Category",
                "verbose_name_plural": "Learning Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="pdfupload",
            options={
                "verbose_name": "PDF Upload",
                "verbose_name_plural": "PDF Uploads",
            },
        ),
    ]
