# Generated by Django 5.0.4 on 2024-07-26 17:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0010_alter_learningcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfupload",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfupload",
            name="name",
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
