# Generated by Django 5.0.4 on 2024-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0011_pdfupload_description_pdfupload_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfupload",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
