# Generated by Django 5.0.4 on 2024-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0012_alter_pdfupload_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
