# Generated by Django 5.0.4 on 2024-07-30 17:11

import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0013_video_video_url_alter_video_video_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AddField(
            model_name="video",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="video",
            name="video_url",
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
