# Generated by Django 5.0.4 on 2024-08-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0014_alter_video_options_video_added_at_and_more"),
        ("inventory", "0046_storage_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfupload",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.branch",
            ),
        ),
    ]
