# Generated by Django 5.0.4 on 2024-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0015_pdfupload_branch"),
        ("inventory", "0046_storage_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfupload",
            name="branch",
        ),
        migrations.AddField(
            model_name="pdfupload",
            name="branches",
            field=models.ManyToManyField(blank=True, to="inventory.branch"),
        ),
    ]
