# Generated by Django 3.2.16 on 2023-01-29 12:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TipsInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tips across whole library', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('due_done', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Task availability', max_length=1)),
                ('tips', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tips.tips')),
            ],
            options={
                'ordering': ['due_done'],
                'permissions': (('can_mark_returned', 'Set tips as returned'),),
            },
        ),
    ]
