# Generated by Django 3.2.16 on 2023-01-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20230129_1230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tips',
            new_name='Tip',
        ),
        migrations.DeleteModel(
            name='TipsInstance',
        ),
    ]
