# Generated by Django 3.2.16 on 2023-01-29 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20230129_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='test',
        ),
        migrations.AddField(
            model_name='tip',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tip',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
