# Generated by Django 3.2.16 on 2023-01-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_tip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='title',
        ),
    ]
