# Generated by Django 3.2.16 on 2023-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_remove_tip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='title',
            field=models.CharField(default='Tip', max_length=50),
            preserve_default=False,
        ),
    ]
