# Generated by Django 3.2.16 on 2023-01-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_tip_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='title',
            new_name='note',
        ),
    ]
