# Generated by Django 3.2.16 on 2023-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_rename_title_tip_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='note',
            field=models.CharField(default='Tip', max_length=50),
        ),
    ]
