# Generated by Django 4.0.8 on 2023-10-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_assignedtip'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtip',
            name='minutes',
            field=models.FloatField(default=0),
        ),
    ]
