# Generated by Django 4.0.8 on 2023-10-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_assignedtip_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtip',
            name='date',
            field=models.DateField(),
        ),
    ]
