# Generated by Django 4.0.8 on 2023-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_alter_assignedtip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtip',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
