# Generated by Django 4.0.8 on 2023-10-09 20:40

from django.db import migrations, models
from django.db.models.functions import TruncDate


def migrate_date(apps, schema_editor):
    MyModel = apps.get_model("tips", "assignedtip")
    MyModel.objects.update(assignedtip_date=TruncDate('date'))

class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_alter_assignedtip_date'),
    ]

    operations = [
        migrations.AddField(model_name='assignedtip', name='assignedtip_date', field=models.DateField(null=True)
        ),
        migrations.RunPython(migrate_date),
        migrations.RemoveField(model_name='assignedtip', name='date'),
        migrations.RenameField(model_name='assignedtip', old_name='assignedtip_date', new_name='date'),
    ]