# Generated by Django 4.0.8 on 2023-10-09 20:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tips', '0015_alter_assignedtip_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedtip',
            unique_together={('user', 'date')},
        ),
    ]
