# Generated by Django 4.0.8 on 2023-09-17 17:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcedureTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter procedure type.", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Enter a brief description of the task",
                        max_length=1000,
                    ),
                ),
                (
                    "type",
                    models.ManyToManyField(
                        help_text="Select a type for this procedure",
                        to="procedures.proceduretypes",
                    ),
                ),
            ],
        ),
    ]
