# Generated by Django 4.0.8 on 2023-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procedures", "0002_addtypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="date_done",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
