# Generated by Django 4.0.8 on 2023-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("procedures", "0003_procedure_date_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which groups should be assigned for the task",
                to="auth.group",
            ),
        ),
    ]
