# Generated by Django 4.0.8 on 2023-09-19 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procedures", "0007_remove_procedure_category_procedure_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Select which category should be assigned for the task",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="procedures.procedurecategories",
            ),
        ),
    ]
