# Generated by Django 5.0.4 on 2024-07-18 10:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0010_procedure_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Enter a brief description of the task",
                verbose_name="Summary",
            ),
        ),
    ]
