# Generated by Django 5.0.4 on 2024-07-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0011_alter_procedure_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procedurecategory",
            options={"verbose_name_plural": "Procedure Categories"},
        ),
    ]
