# Generated by Django 4.2.6 on 2023-11-08 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iaroapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "Branches"},
        ),
    ]
