# Generated by Django 4.2.6 on 2023-11-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_product_storage"),
        ("iaroapp", "0003_addbranches"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="storages",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.storage",
            ),
        ),
    ]
