# Generated by Django 5.0 on 2023-12-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaroapp', '0005_remove_branch_storages_branch_storages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
