# Generated by Django 5.0 on 2023-12-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iaroapp', '0006_delete_branch'),
    ]

    operations = [
       migrations.RunSQL("DROP TABLE IF EXISTS tips_assignedtip"),
       migrations.RunSQL("DROP TABLE IF EXISTS tips_tip"),
    ]
