# Generated by Django 5.0.1 on 2024-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
