# Generated by Django 5.0.4 on 2024-10-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_employeerating_comment"),
        ("shifts", "0005_alter_shift_end_date_alter_shift_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ratings.employeerating",
            ),
        ),
    ]
