# Generated by Django 5.0.4 on 2024-11-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0006_alter_shift_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="planday_shift_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
