# Generated by Django 5.0.4 on 2024-11-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0007_shift_planday_shift_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
