# Generated by Django 4.2.6 on 2023-11-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_addstorages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.storage'),
        ),
    ]
