# Generated by Django 4.2.6 on 2023-11-08 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_addstorages"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.storage",
            ),
        ),
    ]
