# Generated by Django 4.2.6 on 2023-11-13 12:19

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_category_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(default=''),
        ),
    ]
