# Generated by Django 4.2.6 on 2023-11-22 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_productstorage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="value",
        ),
        migrations.RemoveField(
            model_name="product",
            name="value_intended",
        ),
    ]
