# Generated by Django 4.2.6 on 2023-11-23 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_alter_seller_options_remove_product_storage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
