# Generated by Django 4.2.7 on 2023-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='storages',
            field=models.ManyToManyField(to='inventory.storage'),
        ),
    ]
