# Generated by Django 4.2.7 on 2023-12-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_branch_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='departmentId',
            field=models.CharField(default='', max_length=500),
        ),
    ]
