# Generated by Django 4.2.7 on 2023-12-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_branch_departmentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstorage",
            name="main_storage",
            field=models.BooleanField(default=False),
        ),
    ]
