# Generated by Django 5.0.4 on 2024-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_product_internally_produced'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='technical_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
