# Generated by Django 5.0.4 on 2024-06-20 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_alter_productstorage_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstorage",
            name="threshold",
            field=models.FloatField(
                default=30.0,
                help_text="Enter the amount of the item, when it needs to get bought.",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
