# Generated by Django 5.0.4 on 2024-06-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_alter_productstorage_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.branch",
            ),
            preserve_default=False,
        ),
    ]
