# Generated by Django 5.0.4 on 2024-06-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_product_branch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branch",
            old_name="technical_name",
            new_name="tech_name",
        ),
    ]
