# Generated by Django 5.0.4 on 2024-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_rename_technical_name_branch_tech_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seller",
            options={"verbose_name_plural": "Sellers"},
        ),
        migrations.RemoveField(
            model_name="seller",
            name="internal",
        ),
        migrations.AddField(
            model_name="seller",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("shopping_list", "Shopping List"),
                    ("production", "Production"),
                    ("nowhere", "Nowhere"),
                ],
                default="nowhere",
                help_text="Controls where products from this seller appear.",
                max_length=20,
            ),
        ),
    ]
