# Generated by Django 5.0.4 on 2024-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_product_seller_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hint',
            field=models.TextField(help_text='Enter hint for doing inventory. (e.g. Only count 6 packs)', null=True),
        ),
    ]
