# Generated by Django 5.0.1 on 2024-07-08 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0039_product_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="is_weekly",
            field=models.BooleanField(
                default=False,
                help_text="Check if the products of this seller are ordered weekly",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="order_weekday",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                default="monday",
                help_text="If you checked previous option, specify the day on which you order at this seller",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="branch",
            field=models.ForeignKey(
                help_text="Select the branch to define on which shopping list this product should appear",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.branch",
            ),
        ),
    ]
