# Generated by Django 5.0.1 on 2024-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_seller_is_weekly_seller_order_weekday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="hint",
            field=models.TextField(
                blank=True,
                help_text="Enter hint for doing inventory. (e.g. Only count 6 packs)",
                null=True,
            ),
        ),
    ]
