# Generated by Django 5.0.1 on 2024-07-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_alter_product_hint"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstorage",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
