# Generated by Django 5.0.4 on 2024-07-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0043_alter_branch_name_alter_branch_tech_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="units",
            options={"verbose_name_plural": "Units"},
        ),
    ]
