# Generated by Django 5.0.1 on 2024-07-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0044_alter_units_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="storages",
        ),
        migrations.AddField(
            model_name="storage",
            name="branch",
            field=models.ForeignKey(
                help_text="Select a branch for this storage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.branch",
            ),
        ),
    ]
