# Generated by Django 5.0.1 on 2024-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0045_remove_branch_storages_storage_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="storage",
            name="products",
            field=models.ManyToManyField(
                through="inventory.ProductStorage", to="inventory.product"
            ),
        ),
    ]
