# Generated by Django 5.0.4 on 2024-08-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0046_storage_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="departmentId",
            field=models.CharField(
                default="",
                help_text="Planday 'departmentId' associated with the branch.",
                max_length=500,
            ),
        ),
    ]
