# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_auto_20160921_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_joined",
            field=models.DateField(blank=True, null=True, verbose_name="Joined"),
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_quited",
            field=models.DateField(blank=True, null=True, verbose_name="Quited"),
        ),
    ]
