# Generated by Django 1.10 on 2016-09-21 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_auto_20160921_1511"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskinstance",
            name="summary",
        ),
    ]
