# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_auto_20160921_1527"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskinstance",
            options={"ordering": ["due_done"]},
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="tasks.Task"
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular task across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="taskinstance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("d", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="d",
                help_text="Task availability",
                max_length=1,
            ),
        ),
    ]
