# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 10:23
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0017_subject"),
    ]
