# Generated by Django 3.2.16 on 2023-01-25 14:52

from django.db import migrations
from django.contrib.auth.models import Group

def generate_groups(apps, schema_editor):

    Group.objects.get_or_create(name="Director")
    Group.objects.get_or_create(name="Barista")
    Group.objects.get_or_create(name="Service")
    Group.objects.get_or_create(name="Kitchen")

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_auto_20230125_1321'),
    ]

    operations = [
        migrations.RunPython(generate_groups),
    ]
