# Generated by Django 3.2.16 on 2023-02-01 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0034_auto_20230201_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(help_text='Select which groups should be assigned for the task', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
