# Generated by Django 3.2.16 on 2023-02-01 14:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0035_auto_20230201_1434"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.RemoveField(
            model_name="task",
            name="user",
        ),
    ]
