# Generated by Django 3.2.16 on 2023-02-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0037_auto_20230201_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskinstance",
            name="status",
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
