# Generated by Django 3.2.16 on 2023-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0038_auto_20230215_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
