# Generated by Django 3.2.16 on 2023-02-15 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0040_auto_20230215_1249"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskinstance",
            name="borrower",
        ),
        migrations.AddField(
            model_name="taskinstance",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
    ]
