# Generated by Django 3.2.16 on 2023-02-18 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0041_auto_20230215_1253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which groups should be assigned for the task",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which users should be assigned for the task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
