# Generated by Django 4.0.8 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0044_alter_task_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="date_done",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
