# Generated by Django 4.0.8 on 2023-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_remove_taskinstance_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter task type.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this task', to='tasks.tasktypes'),
        ),
    ]
