# Generated by Django 4.0.8 on 2023-09-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_addtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
