# Generated by Django 4.0.8 on 2023-09-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0048_addtypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
    ]
