# Generated by Django 5.0.1 on 2024-01-17 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0051_bakingplaninstance_branch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bakingplaninstance",
            old_name="weekdays",
            new_name="weekday",
        ),
    ]
