# Generated by Django 5.0.1 on 2024-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0058_remove_bakingplaninstance_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakingplaninstance',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
