# Generated by Django 5.0.1 on 2024-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0059_bakingplaninstance_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstance',
            name='preparation',
            field=models.BooleanField(default=False),
        ),
    ]
