# Generated by Django 5.0.1 on 2024-01-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0060_recipeinstance_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weekdays',
            field=models.ManyToManyField(blank=True, help_text='Select weekdays for this task', to='tasks.weekdays'),
        ),
    ]
