# Generated by Django 5.0.1 on 2024-01-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0062_task_parent_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='types',
        ),
    ]
