# Generated by Django 5.0.1 on 2024-02-08 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_productstorage_threshold"),
        ("tasks", "0064_task_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.branch",
            ),
        ),
    ]
