# Generated by Django 5.0.1 on 2024-04-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0065_alter_task_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.branch",
            ),
        ),
    ]
