# Generated by Django 5.0.4 on 2024-05-13 14:34

from django.db import migrations


def fill_branch_id(apps, schema_editor):
    TaskInstance = apps.get_model('tasks', 'TaskInstance')
    TaskInstance.objects.update(branch_id=1)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0068_taskinstance_branch'),
    ]

    operations = [
        migrations.RunPython(fill_branch_id),
    ]
