# Generated by Django 5.0.4 on 2024-06-17 11:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0071_fix_invalid_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="summary",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Enter a brief description of the task. <br>",
                max_length=1000,
                null=True,
            ),
        ),
    ]
