# Generated by Django 5.0.4 on 2024-07-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0072_alter_task_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="app_users",
            new_name="users",
        ),
    ]
