# Generated by Django 5.0.4 on 2024-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0072_alter_task_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
