# Generated by Django 5.0.4 on 2024-07-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0073_task_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="order",
        ),
    ]
