# Generated by Django 3.1.2 on 2020-12-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title', 'author']},
        ),
    ]
