# Generated by Django 3.2.16 on 2023-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20230125_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='weekdays',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=3),
        ),
    ]
