# Generated by Django 5.0.4 on 2024-08-08 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("familienname", models.CharField(max_length=255)),
                ("vorname", models.CharField(max_length=255)),
                ("strasse_hausnummer", models.CharField(max_length=255)),
                ("plz_ort", models.CharField(max_length=100)),
                ("geburtsdatum", models.DateField()),
                (
                    "geschlecht",
                    models.CharField(
                        choices=[("male", "Männlich"), ("female", "Weiblich")],
                        max_length=10,
                    ),
                ),
                (
                    "versicherungsnummer",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "geburtsort_land",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "schwerbehindert",
                    models.CharField(
                        choices=[("yes", "Ja"), ("no", "Nein")], max_length=3
                    ),
                ),
                ("iban", models.CharField(max_length=34)),
                ("bic", models.CharField(max_length=11)),
                ("berufsbezeichnung", models.CharField(max_length=255)),
                ("ausgeubte_tatigkeit", models.CharField(max_length=255)),
                (
                    "beschaftigungsart",
                    models.CharField(
                        choices=[
                            ("main", "Hauptbeschäftigung"),
                            ("secondary", "Nebenbeschäftigung"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weitere_beschaftigung",
                    models.CharField(
                        choices=[("yes", "Ja"), ("no", "Nein")], max_length=3
                    ),
                ),
                (
                    "geringfugige_beschaftigung",
                    models.CharField(
                        choices=[("yes", "Ja"), ("no", "Nein")], max_length=3
                    ),
                ),
                (
                    "hochster_schulabschluss",
                    models.CharField(
                        choices=[
                            ("none", "Ohne Schulabschluss"),
                            ("primary", "Haupt-/Volksschulabschluss"),
                            ("secondary", "Mittlere Reife/gleichwertiger Abschluss"),
                            ("higher", "Abitur/Fachabitur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hochste_berufsausbildung",
                    models.CharField(
                        choices=[
                            ("none", "Ohne beruflichen Ausbildungsabschluss"),
                            ("recognized", "Anerkannte Berufsausbildung"),
                            (
                                "advanced",
                                "Meister/Techniker/gleichwertiger Fachabschluss",
                            ),
                            ("bachelor", "Bachelor"),
                            ("master", "Diplom/Magister/Master/Staatsexamen"),
                            ("doctorate", "Promotion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wochentliche_arbeitszeit",
                    models.CharField(
                        choices=[("fulltime", "Vollzeit"), ("parttime", "Teilzeit")],
                        max_length=10,
                    ),
                ),
                ("steuer_id", models.CharField(max_length=11)),
                ("gesetzliche_krankenkasse", models.CharField(max_length=255)),
                ("date_submitted", models.DateField(default=django.utils.timezone.now)),
                ("unterschrift_arbeitnehmer", models.CharField(max_length=255)),
            ],
        ),
    ]
