# Generated by Django 5.0.4 on 2024-08-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinformation",
            name="geburtsort_land",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="versicherungsnummer",
            field=models.CharField(max_length=20),
        ),
    ]
