# Generated by Django 5.0.4 on 2024-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0003_document_signeddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocument",
            name="request_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="signeddocument",
            name="signing_url",
            field=models.URLField(max_length=1000),
        ),
    ]
