# Generated by Django 5.0.4 on 2024-08-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_signeddocument_request_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocument",
            name="action_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
