# Generated by Django 5.0.4 on 2024-08-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0005_signeddocument_action_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="signeddocument",
            name="signing_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("revoked", "Revoked"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
