# Generated by Django 5.0.4 on 2024-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0006_signeddocument_signing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signeddocument",
            name="signing_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("revoked", "Revoked"),
                    ("unknown", "Unknown"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
