# Generated by Django 5.0.4 on 2024-08-20 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0010_alter_signeddocument_signing_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
