# Generated by Django 5.0.4 on 2024-08-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0011_document_assigned_employees"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="auto_assign_new_employees",
            field=models.BooleanField(
                default=False,
                help_text="Automatically assign this document to all new employees",
            ),
        ),
    ]
