# Generated by Django 5.0.4 on 2024-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_populate_employee_names"),
        ("onboarding", "0012_document_auto_assign_new_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_documents",
                to="employees.employeeprofile",
            ),
        ),
    ]
