# Generated by Django 5.0.4 on 2024-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_populate_employee_names"),
        ("onboarding", "0013_alter_document_assigned_employees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="assigned_employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Currently assigned employees",
                related_name="assigned_documents",
                to="employees.employeeprofile",
            ),
        ),
    ]
