# Generated by Django 5.0.4 on 2024-11-21 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0014_alter_document_assigned_employees"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalinformation",
            old_name="geburtsdatum",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="ausgeubte_tatigkeit",
            new_name="birth_place",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="plz_ort",
            new_name="city_name",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="berufsbezeichnung",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="familienname",
            new_name="health_insurance",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="versicherungsnummer",
            new_name="health_insurance_number",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="geburtsort_land",
            new_name="job_title",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="gesetzliche_krankenkasse",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="strasse_hausnummer",
            new_name="street",
        ),
        migrations.RenameField(
            model_name="personalinformation",
            old_name="steuer_id",
            new_name="tax_id",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="beschaftigungsart",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="geringfugige_beschaftigung",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="geschlecht",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="hochste_berufsausbildung",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="hochster_schulabschluss",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="schwerbehindert",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="unterschrift_arbeitnehmer",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="vorname",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="weitere_beschaftigung",
        ),
        migrations.RemoveField(
            model_name="personalinformation",
            name="wochentliche_arbeitszeit",
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="additional_employment_check",
            field=models.CharField(
                choices=[
                    ("additional_employment_yes", "Yes"),
                    ("additional_employment_no", "No"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="city_zip",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="disability_check",
            field=models.CharField(
                choices=[("disability_yes", "Yes"), ("disability_no", "No")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="emp_type_check",
            field=models.CharField(
                choices=[
                    ("emp_type_main", "Main Employment"),
                    ("emp_type_secondary", "Secondary Employment"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="gender_check",
            field=models.CharField(
                choices=[("gender_male", "Male"), ("gender_female", "Female")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="highest_edu_check",
            field=models.CharField(
                choices=[
                    ("highest_edu_none", "No School Degree"),
                    ("highest_edu_primary", "Primary School"),
                    ("highest_edu_secondary", "Secondary School"),
                    ("highest_edu_higher", "High School/Abitur"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="highest_training_check",
            field=models.CharField(
                choices=[
                    ("highest_training_none", "No Professional Degree"),
                    ("highest_training_recognized", "Recognized Apprenticeship"),
                    ("highest_training_advanced", "Advanced Training/Technician"),
                    ("highest_training_bachelor", "Bachelor"),
                    ("highest_training_master", "Master/Diploma"),
                    ("highest_training_doctorate", "Doctorate"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="insurance_number",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="minor_employment_check",
            field=models.CharField(
                choices=[
                    ("minor_employment_yes", "Yes"),
                    ("minor_employment_no", "No"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="nationality",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinformation",
            name="weekly_hours_check",
            field=models.CharField(
                choices=[
                    ("weekly_hours_fulltime", "Full-time"),
                    ("weekly_hours_halftime", "Part-time"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="date_submitted",
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
