# Generated by Django 5.0.4 on 2024-11-25 20:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding",
            "0015_rename_geburtsdatum_personalinformation_birth_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Slide Title")),
                (
                    "content",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Slide Content"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="additional_employment_check",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=30,
                verbose_name="Additional Employment",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="bic",
            field=models.CharField(max_length=11, verbose_name="BIC"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="birth_date",
            field=models.DateField(verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="birth_place",
            field=models.CharField(max_length=255, verbose_name="Place of Birth"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="city_name",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="city_zip",
            field=models.CharField(max_length=10, verbose_name="City ZIP"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="date_submitted",
            field=models.DateField(auto_now_add=True, verbose_name="Date Submitted"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="disability_check",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=20,
                verbose_name="Disability",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="emp_type_check",
            field=models.CharField(
                choices=[
                    ("main", "Main Employment"),
                    ("secondary", "Secondary Employment"),
                ],
                max_length=20,
                verbose_name="Employment Type",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="gender_check",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="health_insurance",
            field=models.CharField(max_length=255, verbose_name="Health Insurance"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="health_insurance_number",
            field=models.CharField(
                max_length=20, verbose_name="Health Insurance Number"
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="highest_edu_check",
            field=models.CharField(
                choices=[
                    ("none", "No School Degree"),
                    ("primary", "Primary School"),
                    ("secondary", "Secondary School"),
                    ("high", "High School/Abitur"),
                ],
                max_length=30,
                verbose_name="Highest Education",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="highest_training_check",
            field=models.CharField(
                choices=[
                    ("none", "No Professional Degree"),
                    ("recognized", "Recognized Apprenticeship"),
                    ("advanced", "Advanced Training/Technician"),
                    ("bachelor", "Bachelor"),
                    ("master", "Master/Diploma"),
                    ("doctorate", "Doctorate"),
                ],
                max_length=30,
                verbose_name="Highest Training",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="iban",
            field=models.CharField(max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="insurance_number",
            field=models.CharField(max_length=20, verbose_name="Insurance Number"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="job_title",
            field=models.CharField(max_length=255, verbose_name="Job Title"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="minor_employment_check",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=30,
                verbose_name="Minor Employment",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="nationality",
            field=models.CharField(max_length=100, verbose_name="Nationality"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="street",
            field=models.CharField(max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="tax_id",
            field=models.CharField(max_length=11, verbose_name="Tax ID"),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="weekly_hours_check",
            field=models.CharField(
                choices=[("full", "Full-time"), ("part", "Part-time")],
                max_length=30,
                verbose_name="Weekly Working Hours",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(max_length=200, verbose_name="Section Heading"),
                ),
                (
                    "details",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Section Details"
                    ),
                ),
                (
                    "slide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="onboarding.onboardingslide",
                        verbose_name="Slide",
                    ),
                ),
            ],
        ),
    ]
