# Generated by Django 5.0.4 on 2024-11-25 20:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0016_onboardingslide_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingsection",
            name="details",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Section Details"
            ),
        ),
        migrations.AlterField(
            model_name="onboardingslide",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Slide Content"
            ),
        ),
    ]
