# Generated by Django 5.1.3 on 2024-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0017_alter_onboardingsection_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='additional_employment_check',
            field=models.CharField(choices=[('additional_employment_yes', 'Yes'), ('additional_employment_no', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='disability_check',
            field=models.CharField(choices=[('disability_yes', 'Yes'), ('disability_no', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='emp_type_check',
            field=models.CharField(choices=[('emp_type_main', 'Main Employment'), ('emp_type_secondary', 'Secondary Employment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender_check',
            field=models.CharField(choices=[('gender_male', 'Male'), ('gender_female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='highest_edu_check',
            field=models.CharField(choices=[('highest_edu_none', 'No School Degree'), ('highest_edu_primary', 'Primary School'), ('highest_edu_secondary', 'Secondary School'), ('highest_edu_higher', 'High School/Abitur')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='highest_training_check',
            field=models.CharField(choices=[('highest_training_none', 'No Professional Degree'), ('highest_training_recognized', 'Recognized Apprenticeship'), ('highest_training_advanced', 'Advanced Training/Technician'), ('highest_training_bachelor', 'Bachelor'), ('highest_training_master', 'Master/Diploma'), ('highest_training_doctorate', 'Doctorate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='minor_employment_check',
            field=models.CharField(choices=[('minor_employment_yes', 'Yes'), ('minor_employment_no', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='weekly_hours_check',
            field=models.CharField(choices=[('weekly_hours_fulltime', 'Full-time'), ('weekly_hours_halftime', 'Part-time')], max_length=30),
        ),
    ]
