# Generated by Django 5.1.3 on 2024-11-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0018_alter_personalinformation_additional_employment_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='additional_employment_check',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='Additional Employment'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='disability_check',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, verbose_name='Disability'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='emp_type_check',
            field=models.CharField(choices=[('main', 'Main Employment'), ('secondary', 'Secondary Employment')], max_length=20, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender_check',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='highest_edu_check',
            field=models.CharField(choices=[('none', 'No School Degree'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('high', 'High School/Abitur')], max_length=30, verbose_name='Highest Education'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='highest_training_check',
            field=models.CharField(choices=[('none', 'No Professional Degree'), ('recognized', 'Recognized Apprenticeship'), ('advanced', 'Advanced Training/Technician'), ('bachelor', 'Bachelor'), ('master', 'Master/Diploma'), ('doctorate', 'Doctorate')], max_length=30, verbose_name='Highest Training'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='minor_employment_check',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, verbose_name='Minor Employment'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='weekly_hours_check',
            field=models.CharField(choices=[('full', 'Full-time'), ('part', 'Part-time')], max_length=30, verbose_name='Weekly Working Hours'),
        ),
    ]
